#!/usr/bin/env python3
"""Writes deptrac.yaml: the DDD layers of every bounded context and the rules between them (steps/04 §4.1).

    python3 tools/deptrac.py        # from backend/, after adding a context to CONTEXTS

UI → Application → Domain, and Infrastructure → both. A context reaches another only through that context's
Application layer or its domain events (Domain/Event). Shared is the kernel every context may use.
"""

from pathlib import Path

CONTEXTS = [
    'Identity', 'Billing', 'Platform', 'Jobs', 'Questionnaires', 'Responses', 'Reporting', 'Organizations',
    'Assignations', 'Branding', 'Commerce', 'Integrations', 'Content', 'Generation', 'Chat',
]

lines = [
    '# Generated by tools/deptrac.py: edit CONTEXTS there and regenerate, never by hand.',
    '# UI -> Application -> Domain, Infrastructure -> both; another context only through its Application or its events.',
    'deptrac:',
    '  paths:',
    '    - ./src',
    '  layers:',
]


def layer(name: str, regex: str) -> None:
    lines.extend([f'    - name: {name}', '      collectors:', '        - type: classLike', f"          value: '{regex}'"])


def rule(name: str, allowed: list[str]) -> None:
    if not allowed:
        lines.append(f'    {name}: ~')
        return
    lines.append(f'    {name}:')
    lines.extend(f'      - {a}' for a in allowed)


for part in ('Domain', 'Application', 'Infrastructure', 'UI'):
    layer(f'Shared.{part}', rf'^App\\Shared\\{part}\\.*')
for c in CONTEXTS:
    layer(f'{c}.Domain', rf'^App\\{c}\\Domain\\(?!Event\\).*')
    layer(f'{c}.Event', rf'^App\\{c}\\Domain\\Event\\.*')
    layer(f'{c}.Application', rf'^App\\{c}\\Application\\.*')
    layer(f'{c}.Infrastructure', rf'^App\\{c}\\Infrastructure\\.*')
    layer(f'{c}.UI', rf'^App\\{c}\\UI\\.*')

lines.append('  ruleset:')
rule('Shared.Domain', [])
rule('Shared.Application', ['Shared.Domain'])
rule('Shared.Infrastructure', ['Shared.Domain', 'Shared.Application'])
rule('Shared.UI', ['Shared.Domain', 'Shared.Application'])
for c in CONTEXTS:
    others = [o for o in CONTEXTS if o != c]
    other_apps = [f'{o}.Application' for o in others]
    other_events = [f'{o}.Event' for o in others]
    rule(f'{c}.Event', ['Shared.Domain'])
    rule(f'{c}.Domain', ['Shared.Domain', f'{c}.Event'])
    rule(f'{c}.Application', ['Shared.Domain', 'Shared.Application', f'{c}.Domain', f'{c}.Event', *other_apps, *other_events])
    rule(f'{c}.Infrastructure', ['Shared.Domain', 'Shared.Application', 'Shared.Infrastructure', f'{c}.Domain', f'{c}.Event', f'{c}.Application', *other_apps, *other_events])
    rule(f'{c}.UI', ['Shared.Domain', 'Shared.Application', 'Shared.UI', f'{c}.Domain', f'{c}.Event', f'{c}.Application', *other_apps])

Path(__file__).resolve().parent.parent.joinpath('deptrac.yaml').write_text('\n'.join(lines) + '\n', encoding='utf-8')
print('deptrac.yaml written')
