server {
    listen 80;
    server_name _;
    root /app/public;
    client_max_body_size 520m;

    location /build/ {
        try_files $uri =404;
        expires 1h;
        access_log off;
    }

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ ^/index\.php(/|$) {
        fastcgi_pass php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_param DOCUMENT_ROOT /app/public;
        fastcgi_read_timeout 130s;
        fastcgi_buffers 16 32k;
        fastcgi_buffer_size 64k;
        internal;
    }

    location ~ \.php$ {
        return 404;
    }
}
