import {describe, expect, it} from 'vitest';
import {decodeDraft, editorKindOf} from './decode';
import {emptyDraft, newOption, newQuestion} from './draft';
import {encodeFlow} from './encode';
import type {Draft, DraftQuestion} from './types';

type Stored = {
  title: string;
  landing_page: boolean;
  disclaimer: string | null;
  capture_user_data: boolean;
  on_completed: Record<string, unknown> | null;
  questions: {
    title: string;
    category: string | null;
    required: boolean;
    max_followups: number | null;
    acceptance_criteria: string[];
    options: {
      type: string;
      options: {label: string; value: unknown}[];
      validations: {type: string; value: unknown}[];
    }[];
  }[];
};

function questionnaireOf(flow: ReturnType<typeof encodeFlow>): Stored {
  const start = flow.states.find((s) => s.type === 'questionnaire');
  return (start?.parameters as {questionnaire: Stored}).questionnaire;
}

function draftWith(
  question: Partial<DraftQuestion>,
  kind: Draft['kind'] = 'regular',
): Draft {
  return {
    ...emptyDraft(kind),
    title: 'Survey',
    questions: [{...newQuestion(kind, 'Area'), title: 'Q', ...question}],
  };
}

describe('encoding the questions (PRD §10.5)', () => {
  it('gives a non-scored option the slug of its label', () => {
    const flow = encodeFlow(
      draftWith({
        type: 'radio',
        options: [newOption('Muy Bién!'), newOption('Bad')],
      }),
    );
    expect(questionnaireOf(flow).questions[0]!.options[0]).toMatchObject({
      type: 'radio',
      options: [
        {label: 'Muy Bién!', value: 'muy-bien'},
        {label: 'Bad', value: 'bad'},
      ],
    });
  });

  it('sends the scored types as checkbox and radio with the score as value', () => {
    const multiple = encodeFlow(
      draftWith({
        type: 'selection_with_score',
        options: [newOption('A', '1'), newOption('B', '2.5')],
      }),
    );
    expect(questionnaireOf(multiple).questions[0]!.options[0]).toMatchObject({
      type: 'checkbox',
      options: [
        {label: 'A', value: 1},
        {label: 'B', value: 2.5},
      ],
    });
    const single = encodeFlow(
      draftWith({
        type: 'single_selection_with_score',
        options: [newOption('A', '3')],
      }),
    );
    expect(questionnaireOf(single).questions[0]!.options[0]!.type).toBe(
      'radio',
    );
  });

  it('stores a range as min and max validations', () => {
    const flow = encodeFlow(
      draftWith({type: 'range', options: [], rangeMin: '1', rangeMax: '7'}),
    );
    expect(questionnaireOf(flow).questions[0]!.options[0]).toMatchObject({
      type: 'range',
      validations: [
        {type: 'min', value: 1},
        {type: 'max', value: 7},
      ],
    });
  });

  it('stores the text data type as a format validation', () => {
    const format = (textFormat: DraftQuestion['textFormat']) =>
      questionnaireOf(
        encodeFlow(draftWith({type: 'text', options: [], textFormat})),
      ).questions[0]!.options[0]!.validations;
    expect(
      format({preset: 'free', all: true, charsets: []}),
      'All = no rule',
    ).toEqual([]);
    expect(
      format({preset: 'free', all: false, charsets: ['letters', 'numbers']}),
    ).toEqual([{type: 'format', value: 'letters,numbers', message: ''}]);
    expect(format({preset: 'rfc', all: false, charsets: []})).toEqual([
      {type: 'format', value: 'rfc', message: ''},
    ]);
    expect(format({preset: 'phone', all: false, charsets: []})).toEqual([
      {type: 'format', value: 'phone', message: ''},
    ]);
  });

  it('keeps follow-ups and criteria only on text and audio', () => {
    const flow = encodeFlow(
      draftWith({
        type: 'audio',
        options: [],
        maxFollowups: 2,
        criteria: ['Names a tool', ' '],
      }),
    );
    expect(questionnaireOf(flow).questions[0]).toMatchObject({
      max_followups: 2,
      acceptance_criteria: ['Names a tool'],
    });
  });

  it('makes scorable diagnostic questions required', () => {
    const flow = encodeFlow(
      draftWith(
        {
          type: 'range',
          options: [],
          rangeMin: '0',
          rangeMax: '5',
          required: false,
        },
        'diagnostic',
      ),
    );
    expect(questionnaireOf(flow).questions[0]!.required).toBe(true);
  });
});

describe('encoding the flow by type', () => {
  it('a regular questionnaire ends with its thank-you texts and CTA', () => {
    const flow = encodeFlow({
      ...draftWith({options: [newOption('A')]}),
      slug: '',
      disclaimerOn: false,
      disclaimer: 'ignored',
      thankYouOn: true,
      thankYouTitle: 'Thanks!',
      thankYouMessage: 'We read every answer.',
      ctaOn: true,
      cta: {
        title: 'Book a call',
        description: '',
        buttonText: 'Book',
        url: 'https://x.test',
      },
      captureUserData: true,
    });
    expect(flow.slug, 'empty slug = generated by the server').toBeNull();
    expect(flow.result_copy).toEqual({
      title: 'Thanks!',
      subtitle: 'We read every answer.',
    });
    expect(flow.cta).toEqual({
      title: 'Book a call',
      description: null,
      button: {text: 'Book', url: 'https://x.test'},
    });
    expect(flow.states).toHaveLength(1);
    expect(questionnaireOf(flow)).toMatchObject({
      disclaimer: null,
      capture_user_data: true,
      landing_page: true,
    });
  });

  it('a diagnostic sends its tiers in on_completed, a diagnostic state and the layout', () => {
    const draft: Draft = {
      ...draftWith(
        {
          type: 'single_selection_with_score',
          options: [newOption('A', '0'), newOption('B', '5')],
        },
        'diagnostic',
      ),
      tiers: [
        {key: 'a', id: 'low', name: 'Low', description: '', min: '0', max: '2'},
        {
          key: 'b',
          id: 'high',
          name: 'High',
          description: 'Great',
          min: '3',
          max: '5',
        },
      ],
      recommendations: {low: 'Start small', high: ''},
      actions: {high: 'Scale it'},
      blocks: {
        tier: true,
        score: true,
        categories: false,
        recommendations: true,
        action_plan: true,
        pdf: false,
        cta: false,
      },
      resultCopy: {title: ' Your result ', subtitle: ''},
    };
    const flow = encodeFlow(draft);
    expect(flow.states.map((s) => [s.type, s.next ?? null])).toEqual([
      ['questionnaire', 'diagnostic'],
      ['diagnostic', null],
    ]);
    expect(questionnaireOf(flow).on_completed).toEqual({
      type: 'diagnostic',
      tiers: [
        {
          id: 'low',
          name: 'Low',
          description: null,
          min: 0,
          max: 2,
          visible: true,
        },
        {
          id: 'high',
          name: 'High',
          description: 'Great',
          min: 3,
          max: 5,
          visible: true,
        },
      ],
      recommendations: [
        {tier_id: 'low', recommendation: 'Start small', visible: true},
      ],
      action_plan: [{tier_id: 'high', action: 'Scale it', visible: true}],
    });
    expect(flow.layout).toEqual([
      'tier',
      'score',
      'recommendations',
      'action_plan',
    ]);
    expect(flow.result_copy).toEqual({title: 'Your result'});
  });

  it('a chain links the questionnaire, its prompts and the ending', () => {
    const draft: Draft = {
      ...draftWith({options: [newOption('A')]}, 'chaining'),
      prompts: [
        {key: 'a', text: 'one'},
        {key: 'b', text: 'two'},
      ],
      ending: 'diagnostic',
    };
    const flow = encodeFlow(draft, ['prompts/C1/a.txt', 'prompts/C1/b.txt']);
    expect(
      flow.states.map((s) => [s.state_id, s.type, s.next ?? null]),
    ).toEqual([
      ['start', 'questionnaire', 'prompt-1'],
      ['prompt-1', 'prompt', 'prompt-2'],
      ['prompt-2', 'prompt', 'diagnostic'],
      ['diagnostic', 'diagnostic', null],
    ]);
    expect(flow.states[1]!.parameters).toEqual({key: 'prompts/C1/a.txt'});
    const another = encodeFlow({...draft, ending: 'questionnaire'}, [
      'k1',
      'k2',
    ]);
    expect(another.states.at(-1)).toMatchObject({type: 'prompt', next: null});
  });
});

describe('decoding a stored questionnaire', () => {
  const stored = {
    questionnaire_id: 'q1',
    customer_id: 'C1',
    title: 'Maturity',
    description: null,
    disclaimer: 'Private',
    capture_user_data: false,
    landing_page: false,
    type: 'diagnostic' as const,
    is_active: true,
    on_completed: {
      type: 'diagnostic' as const,
      message: null,
      products: null,
      tiers: [
        {
          id: 'low',
          name: 'Low',
          description: null,
          min: 0,
          max: 7,
          visible: true,
        },
      ],
      recommendations: [
        {tier_id: 'low', recommendation: 'Read', action: null, visible: true},
      ],
      action_plan: [],
    },
    parent: 'ROOT',
    question_count: 2,
    is_chain: false,
    slug: 'maturity',
    questions: [
      {
        id: 'x1',
        order: 0,
        title: 'Uses AI?',
        category: 'Usage',
        required: true,
        visibility: [],
        acceptance_criteria: [],
        improvement_message: null,
        flagged_answer: null,
        review: null,
        options: [
          {
            name: 'c1',
            type: 'radio' as const,
            options: [
              {label: 'No', value: 0, visibility: []},
              {label: 'Yes', value: '7', visibility: []},
            ],
            validations: [],
            default_value: null,
            value: null,
            timestamp: null,
            skipped: null,
            locked: null,
          },
        ],
      },
      {
        id: 'x2',
        order: 1,
        title: 'Your RFC',
        category: 'Usage',
        required: false,
        visibility: [],
        acceptance_criteria: [],
        improvement_message: null,
        flagged_answer: null,
        review: null,
        options: [
          {
            name: 'c2',
            type: 'text' as const,
            options: [],
            validations: [
              {
                type: 'format' as const,
                value: 'rfc',
                message: '',
                pattern: null,
              },
            ],
            default_value: null,
            value: null,
            timestamp: null,
            skipped: null,
            locked: null,
          },
        ],
      },
    ],
  };
  const flow = {
    id: 'F1',
    slug: 'maturity',
    detail: '',
    customer_id: 'C1',
    questionnaire_id: 'q1',
    states: [
      {
        state_id: 's',
        type: 'questionnaire' as const,
        parameters: {questionnaire_id: 'q1'},
        outputs: {},
        next: 'd',
      },
      {
        state_id: 'd',
        type: 'diagnostic' as const,
        parameters: {},
        outputs: {},
        next: null,
      },
    ],
    layout: ['tier' as const, 'score' as const],
    result_copy: {title: 'Hi'},
    cta: null,
  };

  it('knows which editor opens it', () => {
    expect(editorKindOf(stored, flow)).toBe('diagnostic');
    expect(
      editorKindOf({...stored, type: 'default', on_completed: null}, flow),
    ).toBe('diagnostic');
    expect(
      editorKindOf(
        {...stored, type: 'default', on_completed: null},
        {...flow, states: [flow.states[0]!]},
      ),
    ).toBe('regular');
    expect(editorKindOf({...stored, is_chain: true}, flow)).toBe('chaining');
    expect(
      editorKindOf(
        {...stored, type: 'quiz_funnel', on_completed: null},
        {...flow, states: [flow.states[0]!]},
      ),
    ).toBe('generic');
  });

  it('reads an all-numeric radio as scored, and the rest back', () => {
    const draft = decodeDraft(stored, flow, [], 'diagnostic');
    expect(draft.title).toBe('Maturity');
    expect(draft.slug).toBe('maturity');
    expect(draft.disclaimerOn).toBe(true);
    expect(draft.questions[0]).toMatchObject({
      id: 'x1',
      type: 'single_selection_with_score',
      category: 'Usage',
    });
    expect(draft.questions[0]!.options.map((o) => [o.label, o.score])).toEqual([
      ['No', '0'],
      ['Yes', '7'],
    ]);
    expect(draft.questions[1]!.textFormat.preset).toBe('rfc');
    expect(draft.tiers.map((t) => [t.id, t.min, t.max])).toEqual([
      ['low', '0', '7'],
    ]);
    expect(draft.recommendations).toEqual({low: 'Read'});
    expect(draft.blocks.tier && draft.blocks.score && !draft.blocks.pdf).toBe(
      true,
    );
    expect(draft.resultCopy).toEqual({title: 'Hi'});
  });

  it('round-trips: decoding what was encoded gives the same flow', () => {
    const draft = decodeDraft(stored, flow, [], 'diagnostic');
    const again = decodeDraft(
      {
        ...stored,
        questions: questionnaireOf(encodeFlow(draft))
          .questions as unknown as typeof stored.questions,
      },
      flow,
      [],
      'diagnostic',
    );
    expect(encodeFlow(again)).toEqual(encodeFlow(draft));
  });

  it('reads a chain back with its prompts and ending', () => {
    const chainFlow = {
      ...flow,
      states: [
        {
          state_id: 's',
          type: 'questionnaire' as const,
          parameters: {},
          outputs: {},
          next: 'p1',
        },
        {
          state_id: 'p1',
          type: 'prompt' as const,
          parameters: {key: 'k1'},
          outputs: {},
          next: 'r',
        },
        {
          state_id: 'r',
          type: 'result' as const,
          parameters: {},
          outputs: {},
          next: null,
        },
      ],
    };
    const draft = decodeDraft(
      {...stored, is_chain: true, type: 'prompt', on_completed: null},
      chainFlow,
      [
        {
          id: 'p',
          questionnaire_id: 'q1',
          customer_id: 'C1',
          s3_path: 'k1',
          order: 0,
          text: 'Ask more',
          outcome: 'result',
        },
      ],
      'chaining',
    );
    expect(draft.prompts.map((p) => p.text)).toEqual(['Ask more']);
    expect(draft.ending).toBe('result');
  });
});
