<?php

declare(strict_types=1);

namespace App\Billing\Infrastructure\Seed;

use App\Billing\Domain\Model\Feature;
use App\Billing\Domain\Model\Plan;
use App\Billing\Domain\Repository\FeatureRepository;
use App\Billing\Domain\Repository\PlanRepository;
use App\Shared\Application\Seed\DemoSeeder;
use App\Shared\Domain\Clock;

/**
 * The feature catalog (PRD §6.3) and four plans. "starter" must exist: it is the trial plan of every sign-up (§6.4).
 * Priced plans carry fake gateway price ids that the fake payment gateway accepts.
 */
final class CatalogSeeder implements DemoSeeder
{
    public const FEATURES = [
        Feature::REGULAR => ['Regular questionnaires', 'Classic questionnaires that end with a thank-you message.'],
        Feature::DIAGNOSTIC => ['Diagnostics', 'Scored questionnaires with tiers, recommendations and an action plan.'],
        Feature::QUIZ_FUNNEL => ['Quiz funnel', 'Store quizzes that recommend products from the catalog.'],
        Feature::CHAIN => ['Chains', 'Questionnaires whose next stage is generated by AI from the answers.'],
        Feature::CHAT => ['AI chat', 'Create and manage questionnaires by chatting with the assistant.'],
        Feature::ORGANIZATIONS => ['Organizations', 'Organizations and their members.'],
        Feature::ASSIGNATIONS => ['Assignations', 'Send questionnaires to organizations and follow them up.'],
        Feature::STYLES => ['Brand styles', 'Your brand applied to the respondent screens.'],
        Feature::ANALYTICS => ['Analytics', 'Answer analytics and dashboard data.'],
        Feature::DASHBOARDS => ['Dashboards', 'AI-designed dashboards per questionnaire.'],
        Feature::USERS => ['Team users', 'Invite your team to the console.'],
        Feature::API => ['External API', 'Read questionnaires and answers with an API key.'],
        Feature::WEBHOOK => ['Webhooks', 'Receive completed responses on your own URL.'],
        Feature::PROFILE => ['Account settings', 'Tracking pixels, file limits and account settings.'],
        Feature::RESPONSES => ['Responses', 'Completed responses (limited by the plan\'s max responses).'],
    ];

    public function __construct(
        private readonly FeatureRepository $features,
        private readonly PlanRepository $plans,
        private readonly Clock $clock,
    ) {
    }

    public static function priority(): int
    {
        return 100;
    }

    public function seed(): void
    {
        $now = $this->clock->now();
        foreach (self::FEATURES as $id => [$name, $description]) {
            if (null === $this->features->find($id)) {
                $this->features->add(new Feature($id, $name, $description, $now));
            }
        }
        foreach (self::plans() as $id => $fields) {
            if (null === $this->plans->find($id)) {
                $this->plans->add(new Plan($id, $fields, $now));
            }
        }
    }

    /** @return array<string, array<string, mixed>> */
    public static function plans(): array
    {
        $limits = static fn (array $limits): array => array_map(
            static fn (string $feature, int $limit): array => ['feature_id' => $feature, 'limit' => $limit],
            array_keys($limits),
            array_values($limits),
        );

        return [
            'starter' => [
                'plan_name' => 'Starter',
                'plan_description' => 'Try Mappi free for a month.',
                'features' => $limits(['regular' => 5, 'diagnostic' => 2, 'quiz-funnel' => 1, 'chain' => 1, 'chat' => 30, 'organizations' => 2, 'assignations' => 5, 'styles' => 2, 'analytics' => -1, 'dashboards' => 1, 'users' => 2, 'profile' => -1]),
                'max_questionnaires' => 5,
                'max_responses' => 100,
                'price_amount' => null,
                'currency' => 'usd',
                'trial_days' => 0,
            ],
            'pro' => [
                'plan_name' => 'Pro',
                'plan_description' => 'For teams that run questionnaires every week.',
                'features' => $limits(['regular' => -1, 'diagnostic' => -1, 'quiz-funnel' => 10, 'chain' => 20, 'chat' => 500, 'organizations' => 50, 'assignations' => 200, 'styles' => 20, 'analytics' => -1, 'dashboards' => 50, 'users' => 10, 'api' => 5000, 'webhook' => 5000, 'profile' => -1]),
                'max_questionnaires' => 50,
                'max_responses' => 5000,
                'price_amount' => 4900,
                'currency' => 'usd',
                'stripe_price_id' => 'price_fake_pro_month',
                'yearly_price_amount' => 47000,
                'stripe_yearly_price_id' => 'price_fake_pro_year',
                'trial_days' => 14,
            ],
            'business' => [
                'plan_name' => 'Business',
                'plan_description' => 'Everything, with room to grow.',
                'features' => $limits(['regular' => -1, 'diagnostic' => -1, 'quiz-funnel' => -1, 'chain' => -1, 'chat' => -1, 'organizations' => -1, 'assignations' => -1, 'styles' => -1, 'analytics' => -1, 'dashboards' => -1, 'users' => 50, 'api' => -1, 'webhook' => -1, 'profile' => -1]),
                'max_questionnaires' => -1,
                'max_responses' => 50000,
                'price_amount' => 14900,
                'currency' => 'usd',
                'stripe_price_id' => 'price_fake_business_month',
                'yearly_price_amount' => 143000,
                'stripe_yearly_price_id' => 'price_fake_business_year',
                'trial_days' => 0,
            ],
            'enterprise' => [
                'plan_name' => 'Enterprise',
                'plan_description' => 'Custom limits, onboarding and support.',
                'features' => $limits(['regular' => -1, 'diagnostic' => -1, 'quiz-funnel' => -1, 'chain' => -1, 'chat' => -1, 'organizations' => -1, 'assignations' => -1, 'styles' => -1, 'analytics' => -1, 'dashboards' => -1, 'users' => -1, 'api' => -1, 'webhook' => -1, 'profile' => -1]),
                'max_questionnaires' => -1,
                'max_responses' => -1,
                'price_amount' => null,
                'currency' => 'usd',
                'trial_days' => 0,
            ],
        ];
    }
}
