/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/customer/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's plan, usage and feature verdicts; loaded once per account by the console (PRD §10.21). */
        get: operations["get_api_customer_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_auth_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_api_auth_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/customer/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_onboarding_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_api_onboarding_set"];
        trace?: never;
    };
    "/api/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A job's state, polled by both apps (PRD §8.5). Public: its id is unguessable. */
        get: operations["get_api_job_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** PRD §8.14: data = the checks; 200 "ok" or 500 "error". */
        get: operations["get_api_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TierOutput: {
            id: string;
            name: string;
            description?: string | null;
            /** Format: float */
            min: number;
            /** Format: float */
            max: number;
            visible: boolean;
        };
        TierTextOutput: {
            tier_id: string;
            /** @default null */
            recommendation: string | null;
            /** @default null */
            action: string | null;
            /** @default null */
            visible: boolean | null;
        };
        OnCompletedOutput: {
            /** @enum {string} */
            type: "default" | "quiz_funnel" | "diagnostic" | "process_mapping";
            /** @default null */
            message: string | null;
            /** @default null */
            products: {
                [key: string]: unknown;
            }[] | null;
            /** @default null */
            tiers: components["schemas"]["TierOutput"][] | null;
            /** @default null */
            recommendations: components["schemas"]["TierTextOutput"][] | null;
            /** @default null */
            action_plan: components["schemas"]["TierTextOutput"][] | null;
        };
        OptionOutput: {
            label: string;
            value?: (string | number) | null;
            visibility: ("male" | "female")[];
        };
        ValidationOutput: {
            /** @enum {string} */
            type: "min" | "max" | "required" | "format";
            /** @default null */
            value: (string | number | boolean) | null;
            /** @default null */
            message: string | null;
            /** @default null */
            pattern: string | null;
        };
        InputControlOutput: {
            name: string;
            /** @enum {string} */
            type: "radio" | "checkbox" | "select" | "range" | "text" | "audio" | "ranking" | "file" | "message" | "email" | "tel" | "phone";
            options: components["schemas"]["OptionOutput"][];
            validations: components["schemas"]["ValidationOutput"][];
            /** @default null */
            default_value: (string | number | boolean) | null;
            /** @default null */
            value: (string | string[]) | null;
            /** @default null */
            timestamp: string | null;
            /** @default null */
            skipped: boolean | null;
            /** @default null */
            locked: boolean | null;
        };
        ReviewOutput: {
            /** @enum {string} */
            status: "approved" | "rejected";
            comment?: string | null;
            reviewed_at?: string | null;
            attempt: number;
        };
        QuestionOutput: {
            id: string;
            order: number;
            title: string;
            description?: string | null;
            disclaimer?: string | null;
            /** @enum {string|null} */
            theme_name?: "gender" | "quote" | "weight" | "height" | "celebration" | "user-capture-data" | "jeans-size" | "weight-composite" | "organization-users-login" | null;
            statements?: unknown;
            visibility: ("male" | "female")[];
            options: components["schemas"]["InputControlOutput"][];
            acceptance_criteria: string[];
            max_followups?: number | null;
            attachment_required?: boolean | null;
            category?: string | null;
            required: boolean;
            /** @default null */
            improvement_message: string | null;
            /** @default null */
            flagged_answer: unknown;
            /** @default null */
            review: components["schemas"]["ReviewOutput"] | null;
        };
        QuestionnaireOutput: {
            questionnaire_id: string;
            customer_id: string;
            title: string;
            description?: string | null;
            disclaimer?: string | null;
            capture_user_data: boolean;
            landing_page: boolean;
            /** @enum {string} */
            type: "default" | "ecommerce" | "quiz_funnel" | "samurai8" | "ai_team_profile" | "diagnostic" | "prompt";
            is_active: boolean;
            on_completed?: components["schemas"]["OnCompletedOutput"] | null;
            /** @description "ROOT" or the id of the chain's root questionnaire */
            parent: string;
            origin_session_id?: string | null;
            session_id?: string | null;
            started_at?: string | null;
            ended_at?: string | null;
            question_count: number;
            is_chain: boolean;
            slug?: string | null;
            questions: components["schemas"]["QuestionOutput"][];
            created_at?: string | null;
            updated_at?: string | null;
        };
        FlowStateOutput: {
            state_id: string;
            /** @enum {string} */
            type: "questionnaire" | "regular" | "quiz_funnel" | "diagnostic" | "prompt" | "result";
            parameters: {
                [key: string]: unknown;
            };
            outputs: {
                [key: string]: unknown;
            };
            next?: string | null;
        };
        CtaOutput: {
            title: string;
            description?: string | null;
            button: {
                text: string;
                url: string;
            };
        };
        FlowOutput: {
            id: string;
            slug: string;
            detail: string;
            states: components["schemas"]["FlowStateOutput"][];
            customer_id: string;
            questionnaire_id: string;
            source_url?: string | null;
            cta?: components["schemas"]["CtaOutput"] | null;
            layout?: ("score" | "tier" | "categories" | "recommendations" | "action_plan" | "pdf" | "cta")[] | null;
            result_copy?: {
                [key: string]: string;
            } | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        SessionOutput: {
            session_id: string;
            questionnaire_id: string;
            customer_id: string;
            title: string;
            description?: string | null;
            disclaimer?: string | null;
            capture_user_data: boolean;
            landing_page: boolean;
            /** @enum {string} */
            type: "default" | "ecommerce" | "quiz_funnel" | "samurai8" | "ai_team_profile" | "diagnostic" | "prompt";
            is_active: boolean;
            on_completed?: components["schemas"]["OnCompletedOutput"] | null;
            parent: string;
            slug?: string | null;
            started_at?: string | null;
            ended_at?: string | null;
            flow_id?: string | null;
            /** @enum {string} */
            status: "filling" | "filled_out" | "processing" | "completed";
            user_data?: {
                name?: string;
                email?: string;
                phone?: string;
            } | null;
            assignations_id?: string | null;
            organization_user_id?: string | null;
            /** @enum {string|null} */
            assignation_type?: "follow_up" | null;
            attempt: number;
            question_count: number;
            questions: components["schemas"]["QuestionOutput"][];
        };
        ProductOutput: {
            product_id: string;
            name: string;
            description: string;
            /** Format: float */
            price?: number | null;
            image_url?: string | null;
            product_url?: string | null;
        };
        DiagnosticResultOutput: {
            /** @enum {string} */
            type: "diagnostic";
            score: {
                value: number;
                max: number;
            };
            categories: {
                id: string;
                name: string;
                score: number;
                max: number;
            }[];
            tiers: components["schemas"]["TierOutput"][];
            recommendations: components["schemas"]["TierTextOutput"][];
            action_plan: components["schemas"]["TierTextOutput"][];
        };
        SessionResultsOutput: {
            session_id: string;
            customer_id: string;
            questionnaire_id: string;
            cta?: components["schemas"]["CtaOutput"] | null;
            layout?: ("score" | "tier" | "categories" | "recommendations" | "action_plan" | "pdf" | "cta")[] | null;
            result_copy?: {
                [key: string]: string;
            } | null;
            products?: components["schemas"]["ProductOutput"][] | null;
            ai_team_profile?: {
                [key: string]: unknown;
            } | null;
            diagnostic?: components["schemas"]["DiagnosticResultOutput"] | null;
            /** @default null */
            extra: {
                [key: string]: unknown;
            } | null;
        };
        JobOutput: {
            job_id: string;
            /** @enum {string} */
            job_type: "styles" | "profile_customization" | "answer_evaluation" | "linkedin_questionnaire" | "prompt_questionnaire" | "create_quiz_funnel" | "scrape_products" | "process_completed_session" | "chat" | "chat-questionnaire-created" | "chat-questionnaire-drafted" | "chat-questionnaire-approved";
            /** @enum {string} */
            status: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED" | "CANCELLED";
            result?: {
                [key: string]: unknown;
            } | null;
            stage?: string | null;
            created_at: string;
            updated_at: string;
        };
        CustomerPlanOutput: {
            plan_id: string;
            from_at: string;
            to_at: string;
            /** @enum {string} */
            billing_interval: "month" | "year";
            stripe_customer_id?: string | null;
            stripe_subscription_id?: string | null;
            trial_end?: string | null;
            discount?: {
                [key: string]: unknown;
            } | null;
            created_at?: string | null;
            updated_at?: string | null;
        };
        PlanSummaryOutput: {
            id: string;
            plan_name: string;
            plan_description: string;
            max_questionnaires?: number | null;
            max_responses?: number | null;
            price_amount?: number | null;
            currency: string;
            yearly_price_amount?: number | null;
            trial_days: number;
        };
        UsagePeriodOutput: {
            questionnaires_used: number;
            from_at: string;
            to_at: string;
        };
        FeatureVerdictOutput: {
            allowed: boolean;
            /** @enum {string|null} */
            reason?: "NO_PLAN" | "PLAN_INACTIVE" | "PLAN_NOT_FOUND" | "FEATURE_NOT_IN_PLAN" | "FEATURE_LIMIT_REACHED" | "RESPONSE_LIMIT_REACHED" | "QUESTIONNAIRE_LIMIT_REACHED" | null;
            limit?: number | null;
            used: number;
        };
        CustomerUsageOutput: {
            customer_plan?: components["schemas"]["CustomerPlanOutput"] | null;
            plan?: components["schemas"]["PlanSummaryOutput"] | null;
            usage?: components["schemas"]["UsagePeriodOutput"] | null;
            plan_active: boolean;
            features: {
                [key: string]: components["schemas"]["FeatureVerdictOutput"];
            };
        };
        TokenOutput: {
            id_token: string;
            refresh_token: string;
            expires_in: number;
        };
        OnboardingOutput: {
            onboarding_completed: boolean;
        };
        JobEnvelopeOutput: {
            job: components["schemas"]["JobOutput"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_api_customer_usage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plan and usage */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerUsageOutput"];
                };
            };
        };
    };
    post_api_auth_token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOutput"];
                };
            };
            /** @description INVALID_CREDENTIALS */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description TOO_MANY_ATTEMPTS */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_api_auth_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenOutput"];
                };
            };
            /** @description UNAUTHORIZED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_onboarding_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The onboarding flag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingOutput"];
                };
            };
        };
    };
    patch_api_onboarding_set: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The onboarding flag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingOutput"];
                };
            };
            /** @description CUSTOMER_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_job_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnvelopeOutput"];
                };
            };
            /** @description JOB_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_api_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
